# Generated by Django 2.0.2 on 2018-03-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TczHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcz_date', models.DateField(verbose_name='Datum')),
                ('tcz_user_change', models.CharField(default='Frei', max_length=20)),
                ('tcz_court', models.IntegerField()),
                ('tcz_hour', models.IntegerField(default=0)),
                ('tcz_free', models.BooleanField(default=False)),
            ],
        ),
    ]
