# Generated by Django 2.0.2 on 2018-04-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TczCourtStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_date', models.DateField(verbose_name='Datum')),
                ('lock_comment', models.CharField(default='Plätze nicht bespielbar', max_length=100, verbose_name='Kommentar')),
            ],
            options={
                'verbose_name': 'Tennisplatz Information',
                'verbose_name_plural': 'Tennisplatz Informationen',
            },
        ),
    ]
