# Generated by Django 2.0.2 on 2018-04-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TczHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcz_date', models.DateField(verbose_name='Datum')),
                ('tcz_user_change', models.CharField(default='Frei', max_length=20, verbose_name='geändert von')),
                ('tcz_court', models.IntegerField(verbose_name='Platz')),
                ('tcz_hour', models.IntegerField(default=0, verbose_name='Stunde')),
                ('tcz_free', models.BooleanField(default=False, help_text='freier Platz', verbose_name='Frei')),
                ('tcz_trainer', models.BooleanField(default=False, help_text='Stunde mit Trainer', verbose_name='Trainer')),
            ],
            options={
                'verbose_name': 'Tennisplatz reservierte Stunde',
                'verbose_name_plural': 'Tennisplatz reservierte Stunden',
                'ordering': ['tcz_date', 'tcz_court', 'tcz_hour'],
            },
        ),
    ]
